# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pyinstall 
      run: |
        pyinstaller --onefile main.py
        
  release:
    runs-on: macOS-latest
    needs: build
    steps:
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main
        tag: v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
